---
title: "Motifs complexes d'ARN"
subtitle: "BIO7002 - Hiver 2026"
author: "Orateur : Vladimir Reinharz <br> Écrit par : "
date: "2026-02-17"
output: 
    html_document:
      toc: true
      toc-title: "Table des matières"
      toc_float:
        collapsed: false
      toc_depth: 2
bibliography: references.bib 
csl: vancouver.csl
link-citations: true
---

<style type="text/css">

.tocify-header {
  text-indent: initial;
}

.tocify-subheader > .tocify-item {
  text-indent: initial;
  padding-left: 2em;
}

body{ /* Normal  */
    font-size: 14px;
}
  
h1 { /* Header 1 */
  font-size: 22px;
}

h2 { /* Header 2 */
    font-size: 18px;
}

h3 { /* Header 3 */
  font-size: 18px;
}
</style>

# Introduction
Chacun des molécules biologiques ADN, ARN et protéines interviennent dans la transmission de l'information génétique et sont indispensable à tout être vivant. La modélisation structurelle de l'ADN, de l'ARN et des protéines nous permet de comprendre leur fonction, ce qui a des implications dans de nombreux domaines, tels que l'agriculture et la médecine. [@molecularBiology]

La réussite de la modélisation structurelle informatique dépend sur des données nombreuses et équilibrées, ainsi que sur des annotations de qualité. Bien que des progrès significatifs aient été réalisés dans la prédiction de la structure de l'ADN et des protéines, la modélisation de l'ARN demeure plus compliquée en raison du nombre limité de données disponibles et de ses propriétés structurelles, telles que ses motifs. [@RNAFunctionFollowsForm] 

Nous présenterons les raisons pour lesquelles la complexité de la structure de l'ARN rend sa prédiction difficile, ainsi que les différents outils existants pour l'identifier et la prédire.



# ADN, ARN et protéines

Les structures d'ADN et de protéines sont généralement plus faciles à prédire que celles de l'ARN puisqu'elles présentent des structures beaucoup plus consistantes et rigides. En effet, l'ADN présente une structure uniforme de double hélice très prévisible qui consistent d'une série répétitive de paires de bases nucléotidiques suivant des règles d'appariement Watson-Crick (A-T, C-G). Elle suit des règles de géométrie simples qui rendent sa structure stable à l'aide d'interactions hydrophobes et de Van der Waals. De ce fait, la stabilité de la structure de l'ADN permet la conservation de l'information génétique. Ses propriétés de superposition, donc l’empilement des bases azotées les unes sur les autres au centre de la double hélice, facilitemt grandement la modélisation. [@dna]

Les structures de protéines, quant à eux, bénéficient d'un large éventail de données disponibles. La Protein Data Bank (PDB) contient plus de 200 000 structures de protéines annotées, alors qu'il en existe seulement 10 000 pour les structures de l'ARN. Le repliement des protéines est plus prévisible que celui de l'ARN, se basant sur la séquence primaire de la chaîne d'acides aminés. De plus, les protéines contiennent de l'information évolutif, aidant fortement les algorithmes de prédiction à inférer les séquences d'acides aminés en utilisant des alignements de séquences multiples. [@protein]

# Structure d'ARN
La modélisation de l’ARN est difficile, notamment à cause de sa structure. Elle présente une seule chaîne de nucléotides, donc nous perdons les propriétés de superposition offertes par l’ADN (plus possible d’avoir une structure constante de double hélice parfaite). Cette chaîne de nucléotides permet aux interactions d'appariement de bases de se produire entre les nucléotides d'un même brin. Les motifs structurels, comme les hélices et les boucles, sont des éléments de structure secondaire qui résultent de ces interactions. [@RNAStructures] Une boucle est créée lorsqu'un brin d'ARN se replie et forme des paires de bases avec une autre section du même brin, et les hélices sont principalement formées par des empilements de paires de bases Watson-Crick. 

Bien que l'appariement des bases soit souvent considéré en termes de paires Watson-Crick (A-U, C-G), d'autres appariements sont également possibles. [@RNAMotifs] Les paires de bases non-Watson-Crick impliquent différentes interactions nucléotidiques de l'appariement Watson-Crick. (include examples?) Les paires de bases non-Watson-Crick jouent un rôle important dans la stabilisation de la structure tertiaire de l'ARN. Ces interactions tertiaires, appelées modules d'ARN, sont caractérisées par des ensembles de paires de bases non-Watson-Crick orientées et ordonnées. [@RNAStructures]


Les ARNs sont moins annotés que les protéines, surtout puisqu'il est chimiquement plus difficile d'entreprendre des expériences de cristallographie pour définir leurs structures. [@RNAFunctionFollowsForm]

# Représentations des structures secondaires de l'ARN
## Dot-bracket notation
## Programmation dynamique
## L'ARN représenté sous forme de grpahes

# Approches informatiques de la représentation d'ARN
## Pasigraph
## FR3D-python
## CaRNAval
## FuzzTree
## BayesPairing2
## Cantaloops

# Conclusion et perspectives

# Références

---
nocite: '@*'
...
